src/main/java/org/folio/list/repository/ListRepository.java, src/main/java/org/folio/list/services/ListValidationService.java, src/test/java/org/folio/list/service/ListServiceValidateUpdateTest.java
Improve the experience when making a shared list private
=> MODLISTS-9:Improve the experience of making list private

src/main/java/org/folio/list/services/ListService.java, src/test/java/org/folio/list/service/ListServiceTest.java, src/test/resources/json/list/list-inactive.json
https://issues.folio.org/browse/MODLISTS-26
The inactive list is not getting refreshed while the active one does (while creating the list)
=> MODLISTS-26:Inactive list should not have compiling status

src/main/resources/db/changelog/changes/v1.0.0/sql/create-export-details-table.sql, src/main/resources/db/changelog/changes/v1.0.0/sql/create-list-contents-table.sql, src/main/resources/db/changelog/changes/v1.0.0/sql/create-list-details-table.sql, src/main/resources/db/changelog/changes/v1.0.0/sql/create-list-refresh-details-table.sql
https://issues.folio.org/browse/MODLISTS-29
=> MODLISTS-29:add the ON CONFLICT DO NOTHING clause

src/main/resources/db/changelog/changes/v1.0.0/sql/update-list-details-table.sql
https://issues.folio.org/browse/MODLISTS-35
=> MODLISTS-35:Columns missing data in Items details view

NEWS.md, pom.xml
This commit moves us away from SNAPSHOT depdendencies and adds the initial release note to NEWS.md
=> MODLISTS-31 Prep POM for release

src/main/resources/db/changelog/changelog-master.xml, src/main/resources/db/changelog/changes/v1.0.1/changelog-v1.0.1.xml, src/main/resources/db/changelog/changes/v1.0.1/sql/update-list-details-table.sql
https://issues.folio.org/browse/MODLISTS-38
=> populating data to columns

src/main/resources/db/changelog/changes/v1.0.1/changelog-v1.0.1.xml, src/main/resources/db/changelog/changes/v1.0.1/sql/alter-list-details-table.sql
https://issues.folio.org/browse/MODFQMMGR-35
=> increasing column size

src/main/resources/db/changelog/changelog-master.xml, src/main/resources/db/changelog/changes/v1.0.2/changelog-v1.0.2.xml, src/main/resources/db/changelog/changes/v1.0.2/sql/update-list-details-table.sql
https://issues.folio.org/browse/MODLISTS-47
=> Adjust naming and description of canned reports

src/main/java/org/folio/list/domain/ListVersions.java, src/main/resources/db/changelog/changelog-master.xml, src/main/resources/db/changelog/changes/v1.0.3/changelog-v1.0.3.xml, src/main/resources/db/changelog/changes/v1.0.3/sql/create-list-versions-table.sql
https://issues.folio.org/browse/MODLISTS-60
=> create list versions table

src/main/resources/db/changelog/changelog-master.xml, src/main/resources/db/changelog/changes/v1.1.0/changelog-v1.1.0.xml, src/main/resources/db/changelog/changes/v1.1.0/sql/create-list-versions-table.sql
https://issues.folio.org/browse/MODLISTS-60
=> creating list versions table

src/main/resources/swagger.api/list.yaml, src/main/resources/swagger.api/schemas/ListVersionDTO.json
https://issues.folio.org/browse/MODLISTS-72
this PR contains only the DTO file for list versioning. (Required for other story)
=> MODLISTS-72: adding DTO file for list versions part1

src/main/java/org/folio/list/domain/ListEntity.java, src/main/java/org/folio/list/domain/ListRefreshDetails.java, src/main/java/org/folio/list/mapper/ListRefreshMapper.java, src/main/resources/db/changelog/changes/v1.1.0/changelog-v1.1.0.xml, src/main/resources/db/changelog/changes/v1.1.0/sql/update-list-refresh-details-table.sql, src/main/resources/swagger.api/schemas/ListRefreshDTO.json, src/test/java/org/folio/list/mapper/ListRefreshMapperTest.java
https://issues.folio.org/browse/MODLISTS-63
=> MODLISTS-63:Include list_versioning in refresh data

src/main/java/org/folio/list/domain/ListEntity.java, src/main/java/org/folio/list/domain/ListVersion.java
=> Adjust size constraints on ListEntity fields

src/main/java/org/folio/list/mapper/ListEntityMapper.java, src/test/java/org/folio/list/service/ListServiceTest.java
This fixes a bug where the fields property on new lists was getting discarded
=> MODLISTS-81 Add fields to ListEntityMapper

pom.xml, src/main/java/org/folio/list/domain/ListContent.java, src/main/java/org/folio/list/domain/ListContentId.java, src/main/java/org/folio/list/rest/QueryClient.java, src/main/java/org/folio/list/services/ListService.java, src/main/java/org/folio/list/services/UserFriendlyQueryService.java, src/main/java/org/folio/list/services/export/CsvCreator.java, src/main/java/org/folio/list/services/export/ListIdsProvider.java, src/main/java/org/folio/list/services/refresh/DataBatchCallback.java, src/main/java/org/folio/list/services/refresh/ListRefreshService.java, src/main/resources/db/changelog/changes/v1.1.0/changelog-v1.1.0.xml, src/main/resources/db/changelog/changes/v1.1.0/xml/update-list-contents-table.xml, src/test/java/org/folio/list/service/ListServiceGetListContentsTest.java, src/test/java/org/folio/list/service/ListServiceTest.java, src/test/java/org/folio/list/service/UserFriendlyQueryServiceTest.java, src/test/java/org/folio/list/service/export/CsvCreatorTest.java, src/test/java/org/folio/list/service/export/ListIdsProviderTest.java, src/test/java/org/folio/list/service/refresh/DataBatchCallbackTest.java
[MODLISTS-82](https://folio-org.atlassian.net/browse/MODLISTS-82): Change how we identify unique records for lists
=> MODLISTS-82: Change how we identify unique records for lists

src/main/resources/db/changelog/changes/v1.1.1/changelog-v1.1.1.xml
_Describe the purpose of the pull request. Include background information if necessary._
_How does this change fulfill the purpose?_
=> MODLISTS-104 Simplify UPDATE and update user-friendly query

src/main/resources/db/changelog/changes/v1.1.1/changelog-v1.1.1.xml
_Describe the purpose of the pull request. Include background information if necessary._
_How does this change fulfill the purpose?_
=> MODLISTS-204 Fix case in user-friendly query

src/main/java/org/folio/list/services/export/CsvCreator.java
Created a user corsair exp
one has 90305 rows in total
after deleting
90304 rows in total
=> MODLISTS-105: Deleted records cause export failures. Ignore deleted records during export

src/main/java/org/folio/list/controller/ListExceptionHandler.java, src/main/java/org/folio/list/exception/InsufficientEntityTypePermissionsException.java, src/main/java/org/folio/list/services/ListService.java, src/main/java/org/folio/list/services/ListValidationService.java, src/main/java/org/folio/list/services/export/ListExportService.java, src/test/java/org/folio/list/controller/ListControllerCreateTest.java, src/test/java/org/folio/list/service/ListServiceGetListContentsTest.java, src/test/java/org/folio/list/service/ListServiceGetListIdTest.java, src/test/java/org/folio/list/service/ListServiceTest.java, src/test/java/org/folio/list/service/ListServiceValidateCancelExportTest.java, src/test/java/org/folio/list/service/ListServiceValidateCancelRefreshTest.java, src/test/java/org/folio/list/service/ListServiceValidateCreateExportTest.java, src/test/java/org/folio/list/service/ListServiceValidateDeleteTest.java, src/test/java/org/folio/list/service/ListServiceValidateDownloadTest.java, src/test/java/org/folio/list/service/ListServiceValidateGetExportTest.java, src/test/java/org/folio/list/service/ListServiceValidateReadTest.java, src/test/java/org/folio/list/service/ListServiceValidateRefreshTest.java, src/test/java/org/folio/list/service/ListValidationServiceTest.java, src/test/java/org/folio/list/service/export/ListExportServiceTest.java, src/test/java/org/folio/list/utils/TestDataFixture.java
[MODLISTS-112](https://folio-org.atlassian.net/browse/MODLISTS-112): Restrict list access based on a user's permissions
=> MODLISTS-112: Restrict list access based on a user's permissions

src/test/java/org/folio/list/service/ListServiceTest.java
Update tests to use new Fql constructor
=> Update tests to use new Fql constructor

README.md, descriptors/ModuleDescriptor-template.json, src/main/resources/application.yml
Adds a system user description in the module descriptor (see [EUREKA-225](https://folio-org.atlassian.net/browse/EUREKA-225))
- Adds a system user description in the module descriptor to the metadata field
=> EUREKA-225 Add system user to ModuleDescriptor

src/main/java/org/folio/list/rest/EntityTypeClient.java, src/main/java/org/folio/list/services/ListService.java, src/test/java/org/folio/list/service/ListServiceTest.java
=> [MODLISTS-128] Handle new entity types response format from mod-fqm-manager

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/list/rest/ConfigurationClient.java, src/main/java/org/folio/list/services/UserFriendlyQueryService.java, src/main/resources/system-user-permissions.txt, src/test/java/org/folio/list/service/UserFriendlyQueryServiceTest.java
[MODLISTS-145](https://folio-org.atlassian.net/browse/MODLISTS-145): Localize dates in user friendly query
=> MODLISTS-145: Localize dates in user friendly query

src/main/java/org/folio/list/services/export/CsvCreator.java, src/test/java/org/folio/list/service/export/CsvCreatorTest.java
[MODLISTS-135](https://folio-org.atlassian.net/browse/MODLISTS-135): Convert dates to local time when exporting a list
=> [MODLISTS-135] Convert dates to local time when exporting a list

src/main/java/org/folio/list/rest/QueryClient.java, src/main/java/org/folio/list/services/export/CsvCreator.java, src/main/java/org/folio/list/services/export/ListExportService.java, src/main/java/org/folio/list/services/export/ListExportWorkerService.java, src/main/resources/system-user-permissions.txt, src/test/java/org/folio/list/service/export/CsvCreatorTest.java, src/test/java/org/folio/list/service/export/ListExportServiceTest.java, src/test/java/org/folio/list/service/export/ListExportWorkerServiceTest.java
[MODFQMMGR-563](https://folio-org.atlassian.net/browse/MODFQMMGR-563): Use new privileged contents endpoint for export
=> MODFQMMGR-563: Use new privileged contents endpoint for export

src/main/resources/db/changelog/changelog-master.xml, src/main/resources/db/changelog/changes/v2.1.1/changelog-v2.1.1.xml
This commmit updates the column width on 2 description columns by changing its data type from varchar(1024) to text
=> MODLISTS-183 Increase description column widths

src/main/java/org/folio/list/domain/ListEntity.java, src/main/java/org/folio/list/domain/ListVersion.java
This commit removes the size constraint on the description field in ListEntity and ListVersion
_Describe the purpose of the pull request. Include background information if necessary._
_How does this change fulfill the purpose?_
=> MODLISTS-183 Remove description constraints

src/main/java/org/folio/list/services/UserFriendlyQueryService.java, src/test/java/org/folio/list/service/UserFriendlyQueryServiceTest.java
Update UserFriendlyQueryService to properly handle string-based custom fields, introduced in [MODFQMMGR-82](https://folio-org.atlassian.net/browse/MODFQMMGR-82)
=> MODFQMMGR-82: Update UserFriendlyQueryService to handle string-based custom fields

src/main/java/org/folio/list/services/UserFriendlyQueryService.java, src/test/java/org/folio/list/service/UserFriendlyQueryServiceTest.java
Update UserFriendlyQueryService to handle new custom field naming scheme.
=> [MODFQMMGR-376] Update UserFriendlyQueryService to handle new custom field naming scheme

descriptors/ModuleDescriptor-template.json, src/main/resources/system-user-permissions.txt
Update system user permissions to handle changes from [MODFQMMGR-672](https://folio-org.atlassian.net/browse/MODFQMMGR-672)
=> [MODFQMMGR-672] Update system user permissions

src/main/java/org/folio/list/services/MigrationService.java, src/test/java/org/folio/list/service/MigrationServiceTest.java
=> [MODLISTS-189] Fail install if ALL lists fail to migrate

README.md, descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/list/services/CustomTenantService.java, src/main/resources/application.yml, src/test/java/org/folio/list/service/CustomTenantServiceTest.java
Increase default wait time for system user and inroduced new env variable.
We need to to do this change to fix issue during application entitelement mentioned in this log
Related ticket: https://folio-org.atlassian.net/browse/MODFQMMGR-690
=> Increase timeout for system user and extract it into env variable

descriptors/ModuleDescriptor-template.json, src/main/resources/system-user-permissions.txt
[MODFQMMGR-685](https://folio-org.atlassian.net/browse/MODFQMMGR-685): Update system user permissions for transaction ET
=> [MODFQMMGR-685] Update system user permissions for transaction ET

src/main/java/org/folio/list/services/export/CsvCreator.java, src/test/java/org/folio/list/service/export/CsvCreatorTest.java
=> MODLISTS-203:Arabic instance title appears as unreadable code in the exported file

README.md, descriptors/ModuleDescriptor-template.json, src/main/resources/application.yml
[MODLISTS-213](https://folio-org.atlassian.net/browse/MODLISTS-213): Add REFRESH_QUERY_TIMEOUT_MINUTES to module descriptor
=> [MODLISTS-213] Add REFRESH_QUERY_TIMEOUT_MINUTES to module descriptor

src/main/java/org/folio/list/rest/QueryClient.java, src/main/java/org/folio/list/services/refresh/ListRefreshService.java, src/test/java/org/folio/list/service/ListRefreshServiceTest.java
This reverts commit f4eff44cda6a2c98de7ab7952a9f4baa3381c7ce, reversing changes made to 3305907653d89ac8ec26322dbcb3e51dcaa5a5cb.
=> Revert "Merge pull request #192 from folio-org/MODFQMMGR-417"

descriptors/ModuleDescriptor-template.json, src/main/resources/system-user-permissions.txt
[MODFQMMGR-128](https://folio-org.atlassian.net/browse/MODFQMMGR-128) - Support query by Holdings records Electronic access fields 
Add permissions for holdings electronic access.
=> MODFQMMGR-128 - Add permissions for holdings electronic access

descriptors/ModuleDescriptor-template.json, src/main/resources/system-user-permissions.txt
Add new permission inventory-storage.identifier-types.collection.get.
=> MODFQMMGR-819 - Support query by Instance identifiers

descriptors/ModuleDescriptor-template.json, src/main/resources/system-user-permissions.txt
[MODFQMMGR-860](https://folio-org.atlassian.net/browse/MODFQMMGR-860) - Support query by Instance subjects
Add inventory-storage.subject-sources.collection.get, inventory-storage.subject-types.collection.get permissions.
=> MODFQMMGR-860 - Support query by Instance subjects
