.github/workflows/api-doc.yml, .github/workflows/api-lint.yml, .github/workflows/api-schema-lint.yml, Jenkinsfile, src/main/resources/swagger.api/list.yaml
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
(instead of Jenkins-operated CI stages).
=> FOLIO-3678 MODLISTS-1 Use GitHub Workflows api-lint and api-schema-lint and api-doc

src/main/java/org/folio/list/controller/ListController.java, src/test/java/org/folio/list/ModListApplicationTest.java, src/test/java/org/folio/list/context/ReaderDatasourceFallbackTest.java, src/test/java/org/folio/list/context/TestcontainerCallbackExtension.java, src/test/java/org/folio/list/controller/ListConfigurationControllerTest.java
The field name in the API is "private" which can't be used, since it's a Java keyword, so OAS generates the interface with the param name "_private" - Sonar doesn't like that name, so instead, we use "isPrivate"
=> MODLISTS-2 Rename "_private" param in ListController

pom.xml, src/main/java/org/folio/list/configuration/ListAppConfiguration.java, src/main/java/org/folio/list/rest/EntityTypeClient.java, src/main/java/org/folio/list/rest/QueryClient.java, src/main/java/org/folio/list/services/ListService.java, src/main/java/org/folio/list/services/UserFriendlyQueryService.java, src/main/java/org/folio/list/services/export/CsvCreator.java, src/main/java/org/folio/list/services/refresh/ListRefreshService.java, src/test/java/org/folio/list/service/ListRefreshServiceTest.java, src/test/java/org/folio/list/service/ListServiceGetListContentsTest.java, src/test/java/org/folio/list/service/ListServiceTest.java, src/test/java/org/folio/list/service/UserFriendlyQueryServiceTest.java, src/test/java/org/folio/list/service/export/CsvCreatorTest.java
mod-lists: Use the FQM API instead of going to its DB schema
=> Refactor to prevent mod-lists from accessing FQM schema

src/main/resources/db/changelog/changes/v1.0.0/sql/update-list-details-table.sql
Per FOLIO-2447, we should not be using uuid_generate_v4() or anything else from the uuid-ossp extension
=> MODLISTS-3 Remove usages of uuid-ossp

src/main/java/org/folio/list/domain/ListContent.java, src/main/resources/application.yml
This commit enables batch inserts (with a batch size of 50, which is the recommended max value, per
https://docs.jboss.org/hibernate/orm/4.0/devguide/en-US/html/ch04.html
=> MODLISTS-5 Enable batch inserts

descriptors/ModuleDescriptor-template.json
This was set to a 3rd of a GiB before, when what we've been running on in other environments is 10x that, so this commit brings the module descriptor's container memory setting in-line with how we've actually been running the module
=> MODLISTS-12 Update the container memory setting

src/main/java/org/folio/list/services/UserFriendlyQueryService.java, src/test/java/org/folio/list/service/UserFriendlyQueryServiceTest.java
[Update UserFriendlyQueryService to handle contains and notContains operators](https://issues.folio.org/browse/MODLISTS-13)
=> MODLISTS-13: Update UserFriendlyQueryService to handle contains and notContains operators

README.md
This adds the required license and issue tracker stuff (per https://dev.folio.org/guidelines/create-new-repo/) to the README. For both sections, I used mod-settings as a reference. The mod-settings "Additional Information" is generally very good, so I included pretty much the whole section instead of just the issue tracker link.
=> MODLISTS-4 Add missing sections to README

descriptors/ModuleDescriptor-template.json
This commit changes the module's declared dependencies in the module descriptor from "mod-fqm-manager" to the more specific "entity-types" and "query" as the old one is going away and we need to use the more specific ones anyway
=> MODFQMMGR-3 Use more specific FQM interfaces

src/main/resources/swagger.api/schemas/ListAppError.json, src/main/resources/swagger.api/schemas/ListDTO.json, src/main/resources/swagger.api/schemas/ListRefreshDTO.json, src/main/resources/swagger.api/schemas/ListSummaryResultsDTO.json, src/main/resources/swagger.api/schemas/parameters.json
[MODLISTS-22: Fix api-lint errors](https://issues.folio.org/browse/MODLISTS-22)
=> MODLISTS-22: Fix api-lint errors

Dockerfile, pom.xml
[MODLISTS-23: Fix Jenkins build errors](https://issues.folio.org/browse/MODLISTS-23)
=> MODLISTS-23: Fix Jenkins build errors

src/main/resources/db/changelog/changes/v1.0.0/sql/create-list-refresh-details-table.sql, src/main/resources/db/changelog/changes/v1.0.1/changelog-v1.0.1.xml
This moves the changes made since 1.0.0 to a new changelog file in order to make migrations work better
=> MODLISTS-40 Move 1.0.1 DB changes to their own changelog

descriptors/ModuleDescriptor-template.json
This commit makes mod-lists provide the _tenant 2.0 interface, which will make Okapi use the POST /_/tenant API for all tenant actions
=> MODLISTS-46 - Update the provided _tenant interface version

pom.xml, src/main/java/org/folio/list/ModListsApplication.java, src/main/java/org/folio/list/configuration/ListAppConfiguration.java, src/main/java/org/folio/list/services/ListService.java, src/main/java/org/folio/list/services/ListValidationService.java, src/test/java/org/folio/list/service/ListRefreshServiceTest.java, src/test/java/org/folio/list/service/ListServiceGetListContentsTest.java, src/test/java/org/folio/list/service/ListServiceTest.java, src/test/java/org/folio/list/service/ListServiceValidateCreateTest.java, src/test/java/org/folio/list/service/ListServiceValidateUpdateTest.java
https://github.com/folio-org/lib-fqm-query-processor/pull/13 removes essentially the entire `org.folio.fqm.lib` package, with the exception of `FqlValidationService`, which is moved to `org.folio.fql.lib`.  It also adds spring autowiring/etc support to the FQL services.
This PR updates `mod-lists` to accept these new beans and packages.
=> [MODFQMMGR-87] Use new centralized lib patterns

src/main/java/org/folio/list/controller/ListController.java, src/main/java/org/folio/list/domain/ListVersion.java, src/main/java/org/folio/list/mapper/ListVersionMapper.java, src/main/java/org/folio/list/repository/ListVersionRepository.java, src/main/java/org/folio/list/services/ListService.java, src/main/resources/swagger.api/list.yaml, src/test/java/org/folio/list/controller/ListControllerVersionTest.java, src/test/java/org/folio/list/domain/ListVersionTest.java, src/test/java/org/folio/list/mapper/ListVersionMapperTest.java, src/test/java/org/folio/list/service/ListServiceTest.java, src/test/java/org/folio/list/utils/TestDataFixture.java, src/test/resources/json/list/list-version.json
https://issues.folio.org/browse/MODLISTS-61
https://issues.folio.org/browse/MODLISTS-72
This tickets implememts the logic of lists versioning plus we can retrieve the previous versions of lists using get request`lists/{listId}/versions`
=> MODLISTS-61 and MODLISTS-72: Implementing list versioning through end point

descriptors/ModuleDescriptor-template.json, pom.xml, src/main/java/org/folio/list/controller/ListController.java, src/main/java/org/folio/list/exception/VersionNotFoundException.java, src/main/java/org/folio/list/repository/ListVersionRepository.java, src/main/java/org/folio/list/services/ListService.java, src/main/java/org/folio/list/services/ListValidationService.java, src/main/resources/swagger.api/list.yaml, src/test/java/org/folio/list/controller/ListControllerVersionTest.java, src/test/java/org/folio/list/service/ListServiceTest.java
Create an endpoint to `GET` a single version of a list
- Extend existing repository/service/controllers to support a new endpoint.
- Moved logic to ensure a list exists for `/lists/{id}/versions` into the Service rather than the Controller
- Fixed error where a list with no versions (possible after creation) would throw an exception
- Added tests to ensure that we actually save a list's old version when updating (not a super-rigorous test, but better than nothing)
- Will do more in Karate as part of [Jira FAT-10223](https://issues.folio.org/browse/FAT-10223)
=> [MODLISTS-62] Create new list version endpoint

src/main/resources/db/changelog/changes/v1.1.0/changelog-v1.1.0.xml, src/main/resources/db/changelog/changes/v1.1.0/yml/update-list-versions-fkey.yaml
The new `list_versions` table enforced a foreign key constraint which disallowed deletion of the parent entity (lists). This made it impossible to delete lists.
Updates the foreign key constraint to `CASCADE` on deletions.
=> [MODLISTS-74] Delete list versions automatically with parent list

src/main/java/org/folio/list/domain/ListVersion.java, src/main/java/org/folio/list/mapper/ListEntityMapper.java, src/main/java/org/folio/list/services/ListService.java, src/main/resources/db/changelog/changes/v1.1.0/changelog-v1.1.0.xml, src/main/resources/db/changelog/changes/v1.1.0/yml/alter-list-details-updated-metadata-add-not-null-constraint.yaml, src/test/java/org/folio/list/domain/ListVersionTest.java
List version metadata (created by/timestamp) was sourced from the current user/time, however, we should store the list's previous updated information instead.  This will ensure that, when User A's changes get persisted as a historical version (i.e. the list is updated in the future), user A's information and original time get persisted, too. 
Alter list version logic
=> [MODLISTS-75] Source version author information from list rather than session

src/main/java/org/folio/list/services/UserFriendlyQueryService.java, src/test/java/org/folio/list/service/UserFriendlyQueryServiceTest.java
[MODFQMMGR-119](https://issues.folio.org/browse/MODFQMMGR-119): Create new operators to support searching for null/empty values 
This ticket adds a handler for the new $empty FQL operator to the UserFriendlyQueryService.
=> MODFQMMGR-119: Add empty FQL operator handler to UserFriendlyQueryService

README.md, src/main/java/org/folio/list/services/refresh/ListRefreshService.java, src/main/resources/application.yml, src/test/java/org/folio/list/service/ListRefreshServiceTest.java, src/test/java/org/folio/list/service/ListServiceTest.java
This increases the timeout for list refresh queries from 30 minutes to 90 minutes. It also makes it so this value can be configured at runtime via application properties or environment variables
=> MODLISTS-83 Increase the list refresh query timeout and make it configurable

src/main/java/org/folio/list/services/ListService.java, src/main/java/org/folio/list/services/UserFriendlyQueryService.java, src/test/java/org/folio/list/service/UserFriendlyQueryServiceTest.java
Add handling for contains_any and not_contains_any operators in UserFriendlyQueryService to support 
[MODFQMMGR-130](https://folio-org.atlassian.net/browse/MODFQMMGR-130): Add contains_any and not_contains_any operators
=> Add support for contains_any and not_contains_any operators in UserFriendlyQueryService (MODFQMMGR-130)

pom.xml
This commit bumps our Spring Boot dependency from 3.2.0 to 3.2.3 (the lastest stable release). It also bumps our folio-spring-base version from 7.3.0-SNAPSHOT to 8.1.0, to keep our Spring-based transitive dependencies in line with the updated Spring Boot version
=> MODLISTS-88 Bump the Spring Boot dependency version

src/main/java/org/folio/list/controller/ListController.java, src/main/java/org/folio/list/services/ListService.java, src/main/resources/swagger.api/list.yaml, src/test/java/org/folio/list/controller/ListControllerListContentsTest.java, src/test/java/org/folio/list/service/ListServiceGetListContentsTest.java
Temporary change to retrieve contents for all fields in entity type definition. This will keep things working until the UI is updated to send desired fields in contents request. This PR also provides support for passing the list of fields to retrieve content for in the GET /lists/contents API, although the UI will need to be updated to support that change.
Fix for [MODLISTS-90](https://folio-org.atlassian.net/browse/MODLISTS-90): Newly selected columns aren't populated with data
=> Pass fields in GET /lists/contents request. Retrieve all fields if "fields" parameter is not provided

src/main/java/org/folio/list/controller/ListExportController.java, src/main/java/org/folio/list/domain/ExportDetails.java, src/main/java/org/folio/list/mapper/ListExportMapper.java, src/main/java/org/folio/list/services/export/CsvCreator.java, src/main/java/org/folio/list/services/export/ListExportService.java, src/main/resources/db/changelog/changes/v1.1.0/changelog-v1.1.0.xml, src/main/resources/swagger.api/list.yaml, src/main/resources/swagger.api/schemas/ListExportDTO.json, src/test/java/org/folio/list/controller/ListExportControllerTest.java, src/test/java/org/folio/list/service/export/CsvCreatorTest.java, src/test/java/org/folio/list/service/export/ListExportServiceTest.java
Accept list of fields to export in export request body. This will fix [MODLISTS-91](https://folio-org.atlassian.net/browse/MODLISTS-91) by allowing columns saved in local storage to be exported.
If there is no request body, then the fields from the list entity are used instead.
=> MODLISTS-91: Accept list of fields to export in export request body

.gitignore, src/main/java/org/folio/list/services/ListService.java, src/test/java/org/folio/list/service/ListServiceTest.java
Before, if a list was edited and no fields were included, we would add all fields to it. However, there are legitimate cases where a list could be edited and no fields included (e.g. just name/description); in these cases, we should use the list of fields from before the edit.
=> [MODLISTS-94] Check existing list of fields on list update

src/main/java/org/folio/list/controller/ListExceptionHandler.java, src/test/java/org/folio/list/controller/ListExceptionHandlerTest.java
Wrap unhandled exceptions in a generic wrapper, so that the UI can handle them better
It adds a handler for all Exceptions, so that any without a more specific handler can still be handled
=> MODLISTS-59 Add generic exception handler

src/main/java/org/folio/list/services/UserFriendlyQueryService.java, src/test/java/org/folio/list/service/UserFriendlyQueryServiceTest.java
This adds support for displaying nested properties in user friendly queries, e.g. `fund_distribution[*]->code`.
This was added by replacing calls to `.getColumnName()` (which truncates any extra stuff from the root column) with `.serialize()`, which yields the entire (expected) field name.
=> [MODLISTS-86] Support nested properties in user friendly queries

src/main/resources/db/changelog/changelog-master.xml, src/main/resources/db/changelog/changes/v1.1.1/changelog-v1.1.1.xml
This fixes the Missing Items list by converting all of the condition values from lower case to sentence case, to match the available values provided in the Items entity type
=> MODLISTS-104 Fix the condition values in Missing Items

src/main/java/org/folio/list/services/export/CsvCreator.java, src/test/java/org/folio/list/service/export/CsvCreatorTest.java
[MODLISTS-93](https://folio-org.atlassian.net/browse/MODLISTS-93)
With this change, only selected columns will be exported (instead of exporting all columns, but only selected data)
=> MODLISTS-93: Include expected columns and data in list export

src/main/java/org/folio/list/services/export/ListExportService.java, src/test/java/org/folio/list/service/export/ListExportServiceTest.java
Solving a bug introduced in [MODLISTS-93](https://folio-org.atlassian.net/browse/MODLISTS-93). Always include all ID columns in export so that export can complete without errors.
=> Always include ID columns in export

src/main/java/org/folio/list/services/ListService.java, src/test/java/org/folio/list/service/ListServiceTest.java
GET /lists throws a 500 if there are no valid entity types available to the user. Fix this by just returning an empty page in this scenario.
=> getAllLists: return empty list summary when searchEntityTypeIds is empty

src/main/java/org/folio/list/mapper/ListMigrationMapper.java, src/main/java/org/folio/list/rest/EntityTypeClient.java, src/main/java/org/folio/list/services/CustomTenantService.java, src/main/java/org/folio/list/services/ListService.java, src/main/java/org/folio/list/services/ListValidationService.java, src/main/java/org/folio/list/services/MigrationService.java, src/main/java/org/folio/list/services/UserFriendlyQueryService.java, src/main/java/org/folio/list/services/export/CsvCreator.java, src/main/java/org/folio/list/services/export/ListExportService.java, src/test/java/org/folio/list/mapper/ListMigrationMapperTest.java, src/test/java/org/folio/list/rest/EntityTypeClientTest.java, src/test/java/org/folio/list/service/CustomTenantServiceTest.java, src/test/java/org/folio/list/service/ListServiceGetListContentsTest.java, src/test/java/org/folio/list/service/ListServiceTest.java, src/test/java/org/folio/list/service/ListServiceValidateCancelExportTest.java, src/test/java/org/folio/list/service/ListServiceValidateReadTest.java, src/test/java/org/folio/list/service/UserFriendlyQueryServiceTest.java, src/test/java/org/folio/list/service/export/CsvCreatorTest.java, src/test/java/org/folio/list/service/export/ListExportServiceTest.java
It was all fun and games, but then:
I had to do a bit of refactoring to solve this, which IMO is an overall improvement. Two main things were done as part of this:
- convenience methods for getting user friendly queries for `ListEntity`s (rather than just FqlConditions) were moved to `UserFriendlyQueryService`
- wrapped versions of `EntityTypeClient.getEntityType` which include specific exception handling (for not found, permissions, etc) were consolidated into a new overloaded method inside `EntityTypeClient`. This improves complexity for this error handling across several locations, and enables all parts of the code to easily leverage this.
=> [MODLISTS-126] Invoke migration methods on install and GET /lists

pom.xml, src/main/java/org/folio/list/services/CustomTenantService.java, src/test/java/org/folio/list/service/CustomTenantServiceTest.java
This commit adds retry logic to the tenant initialization service, around the query migration operation, since the necessary permissions on the system user can take a bit of time when initially creating a eureka tenant
=> MODLISTS-155 MODFQMMGR-550 Add retry logic to tenant initialization

descriptors/ModuleDescriptor-template.json, src/main/resources/system-user-permissions.txt
This commit brings the list of system user permissions in the module descriptor and system-user-permissions.txt in line with each other, as they are used for different systems
=> MODLISTS-157 Synchronize system user permissions

src/main/java/org/folio/list/rest/ConfigurationClient.java, src/main/java/org/folio/list/rest/ConfigurationClientRaw.java, src/main/java/org/folio/list/services/UserFriendlyQueryService.java, src/test/java/org/folio/list/rest/ConfigurationClientTest.java, src/test/java/org/folio/list/service/UserFriendlyQueryServiceTest.java
The frontend uses the date being analyzed to get the offset (4 or 5 as applicable):
- midnight Oct 1 New York time is in UTC-4, so it gets `2024-10-01T04:00:00Z`
- midnight Dec 1 New York time is in UTC-5, so it gets `2024-12-01T05:00:00Z`
However, the backend was using the current date to determine the UTC offset, which resulted in either four or five hours, depending on the date that the server handled the request.
We didn't see this before (during DST) as we calculated an offset of 5, so when truncated to just the date it looked correct.
=> [MODLISTS-161] Consider daylight savings when determining dates to show for user-friendly queries

descriptors/ModuleDescriptor-template.json
This commit adds the "configuration" interface to the "requires" section of the module descriptor. This commit also rearranges that section, sorting it alphabetically.
=> MODLISTS-160 Add a missing interface to the MD

src/main/java/org/folio/list/configuration/SystemUserFeignConfig.java, src/main/java/org/folio/list/rest/SystemUserClient.java, src/main/java/org/folio/list/rest/SystemUserQueryClient.java, src/main/java/org/folio/list/services/export/CsvCreator.java, src/test/java/org/folio/list/rest/SystemUserClientTest.java, src/test/java/org/folio/list/service/export/CsvCreatorTest.java
[MODLISTS-158](https://folio-org.atlassian.net/browse/MODLISTS-158): Exports fail during S3 upload
Addresses 2 problems with exports:
1. Failures during S3 upload (solved by retrying upload with exponential backoff)
2. Failures due to system user token expiring mid-export (solved by new feign client implementation that re-authenticates system user and updates token)
=> MODLISTS-158: Retry failed S3 uploads during export

src/main/java/org/folio/list/configuration/SystemUserFeignConfig.java
[MODLISTS-165](https://folio-org.atlassian.net/browse/MODLISTS-165): Use custom SystemUserClient only when system user is enabled
=> MODLISTS-165: Use custom SystemUserClient only when system user is enabled

src/main/java/org/folio/list/rest/EntityTypeClient.java, src/main/java/org/folio/list/services/UserFriendlyQueryService.java, src/test/java/org/folio/list/rest/EntityTypeClientTest.java, src/test/java/org/folio/list/service/UserFriendlyQueryServiceTest.java
This commit updates our approach to generating user-friendly queries, so that it includes hidden fields in the entity types it uses to look up things like field metadata
=> MODLISTS-175 Include hidden fields in UFQ generation

src/main/java/org/folio/list/services/CustomTenantService.java, src/main/java/org/folio/list/services/MigrationService.java
This commit makes it so the list migration service will catch and log errors that happen when migrating lists, as we don't want edge cases and invalid lists to break the whole module or break the installation process
=> MODLISTS-178 Make migration errors non-fatal

pom.xml
https://folio-org.atlassian.net/browse/MODLISTS-187
Fix security vulnerabilities in Spring Boot and S3 dependencies.
Upgrade Spring Boot from 3.2.3 to 3.3.7.
Note that OSS support for Spring Boot 3.2.x has ended 2024-11-23: https://spring.io/projects/spring-boot#support
Note that Ramsons requires Spring Boot 3.3.x: https://folio-org.atlassian.net/wiki/spaces/TC/pages/5058042/Ramsons#Ramsons-ThirdPartyLibraries/Frameworks
Upgrade folio-s3-client from 2.1.0 to 2.2.1.
Upgrade aws s3 client from 2.19.2 to 2.29.47.
folio-s3-client.version 2.2.1 only needs aws s3, not the complete aws-sdk-java: https://github.com/folio-org/folio-s3-client/blob/v2.2.1/pom.xml#L62-L65
folio-s3-client.version 2.2.1 ships with snappy-java 1.1.10.7, no need to downgrade snappy-java.
The aws s3 client upgrade …
=> MODLISTS-187: Spring Boot 3.3.7, folio-s3-client 2.2.1, aws s3 2.29.47

NEWS.md, pom.xml, src/main/java/org/folio/list/controller/ListExportController.java, src/main/java/org/folio/list/services/export/ListExportService.java, src/test/java/org/folio/list/controller/ListExportControllerTest.java, src/test/java/org/folio/list/service/export/ListExportServiceTest.java
Turns out, sending a resource/stream to Spring directly with no `Content-Length` will cause the entire stream to be read so the content length can be determined. There is no point to this (especially since Okapi strips the `Content-Length` header!!), but we're now avoiding the massive overhead that occurs with all that stream reading.
Additionally, as an extra speedup in the export process, I added `caffeine`, which allows the system user library to use its internal cache and prevent constantly re-authenticating for each export batch.
=> [MODLISTS-188] Stream export downloads directly without buffering

src/main/java/org/folio/list/controller/ListExportController.java, src/test/java/org/folio/list/controller/ListExportControllerTest.java
The content type for streaming has been changed so that Sidecars can correctly handle it; otherwise, it cannot be determined that it is a stream.
https://folio-org.atlassian.net/browse/MODLISTS-192
=> MODLISTS-192: Updates stream headers to resolve issues with sidecars.

src/main/java/org/folio/list/services/CustomTenantService.java, src/test/java/org/folio/list/service/CustomTenantServiceTest.java
In case when a system user has not been created yet mod-fqm tries to invoke mod-roles-keycloak and fails because of the absence of system user and in this case we have FeignException.
As solution we can add this exception for retry
Note: system user in Eureka started to creating before invoking POST Tenant API
=> Add general FeignException for retry logic

src/main/java/org/folio/list/services/CustomTenantService.java, src/test/java/org/folio/list/service/CustomTenantServiceTest.java
In logs we see that FeignException has 2 wrappers before it. 
So need to make more generic logic to handle all possible causes
=> Improve handling of retries by checking all nested causes

src/main/resources/db/changelog/changelog-master.xml, src/main/resources/db/changelog/changes/v2.1.2/changelog-v2.1.2.xml
These fields cause unexpected behavior in the UI when the canned lists are duplicated
Remove the offending fields
=> MODLISTS-211 Remove non-essential fields from canned lists

descriptors/ModuleDescriptor-template.json, src/main/resources/system-user-permissions.txt
Add back config perm back to system user. I removed it prematurely, since it's still necessary until [MODFQMMGR-746](https://folio-org.atlassian.net/browse/MODFQMMGR-746) is completed
=> Temporarily add config permissions back to system user

descriptors/ModuleDescriptor-template.json, src/main/resources/system-user-permissions.txt
This reverts commit 33350bdb08abc2f51b8c1ae56778e44c98552d6d.
Revert https://github.com/folio-org/mod-lists/pull/236 as we are not exposing mod-linked-data via lists.
_How does this change fulfill the purpose?_
=> Revert - [MODFQMMGR-971] Add Linked Data permissions (#236)
